{{-- resources/views/reports/_pdf_header.blade.php --}}
{{-- Body content only — must be @include'd from <body>, NOT <head>. mPDF (unlike
     DomPDF) strips any non-<style> markup found inside <head>, so this used to
     silently disappear from the rendered PDF. Styles live in _pdf_style.blade.php. --}}
<table class="hdr-table">
  <tr>
    {{-- LEFT: Dealer info --}}
    <td class="hdr-left">
      @if(!empty($data['dealer']))
        <div class="dealer-name">
          {{ $data['dealer']['business_name'] ?? $data['dealer']['name'] ?? '' }}
        </div>
        @if(!empty($data['dealer']['city']))
          <div class="dealer-sub">{{ $data['dealer']['city'] }}</div>
        @endif
      @endif
    </td>

    {{-- CENTRE: Logo (base64 embedded — no remote fetch needed at render time) --}}
    <td class="hdr-mid">
      @php
        $logoPath  = public_path('images/greenwave-logo.jpg');
        $logoCache = public_path('images/greenwave-logo-b64.txt');
        if (!file_exists($logoCache)) {
            if (!file_exists(public_path('images'))) {
                mkdir(public_path('images'), 0755, true);
            }
            $raw = @file_get_contents('https://g2app.in/images/greenwave-logo-1-275-sl.jpg');
            if ($raw) {
                file_put_contents($logoPath, $raw);
                file_put_contents($logoCache, base64_encode($raw));
            }
        }
        $logoB64 = file_exists($logoCache) ? file_get_contents($logoCache) : null;
      @endphp
      @if($logoB64)
        <img src="data:image/jpeg;base64,{{ $logoB64 }}" alt="Greenwave" class="logo-img" />
      @else
        <span class="logo-fallback">GREENWAVE</span>
      @endif
    </td>

    {{-- RIGHT: Report title + generated by --}}
    <td class="hdr-right">
      <div class="report-title-block">{{ $title ?? '' }}</div>
      @if(!empty($data['dealer']))
        <div class="generated-by">
          Generated by:
          <strong>{{ $data['dealer']['business_name'] ?? $data['dealer']['name'] ?? '' }}</strong>
        </div>
      @endif
      <div class="generated-by">
        {{ \Carbon\Carbon::now()->format('d M Y, h:i A') }}
      </div>
    </td>
  </tr>
</table>

<div class="hdr-rule-1"></div>
<div class="hdr-rule-2"></div>

<table class="meta-row">
  <tr>
    <td class="meta-left">
      @if(!empty($data['ctx']->dateFrom) || !empty($data['ctx']->dateTo))
        <span class="meta-chip">
          <span class="meta-chip-lbl">Period</span>
          <span class="meta-chip-val">
            {{ !empty($data['ctx']->dateFrom) ? \Carbon\Carbon::parse($data['ctx']->dateFrom)->format('d M Y') : '—' }}
            &ndash;
            {{ !empty($data['ctx']->dateTo) ? \Carbon\Carbon::parse($data['ctx']->dateTo)->format('d M Y') : '—' }}
          </span>
        </span>
      @endif
    </td>
    <td class="meta-right">
      <span class="confidential-badge">Greenwave &bull; Confidential</span>
    </td>
  </tr>
</table>

<div class="sec-title">
  {{ $subtitle ?? $title ?? '' }}
</div>
