<?php

namespace App\Helpers;

use App\Attendance;
use App\Holiday;
use Carbon\Carbon;

/**
 * ---------------------------------------------------------------
 * AttendanceHelper
 * ---------------------------------------------------------------
 * This helper builds a normalized attendance dataset for:
 *  - PDF export
 *  - Web attendance table
 *  - APIs or analytics layer
 *
 * Includes:
 *  ✔ Holiday rules
 *  ✔ Leave logic
 *  ✔ Late counter logic
 *  ✔ Half day & second-half leave logic
 *  ✔ Salary calculation value (calc)
 *  ✔ Editable flag (is_edited_by_admin)
 */
class AttendanceHelper
{
    /**
     * ---------------------------------------------------------------
     * getMonthlyAttendance()
     * ---------------------------------------------------------------
     * Creates a complete attendance listing for a selected:
     *  - Employee
     *  - Month
     *  - Year
     *
     * It loops through each day of the month and evaluates:
     *  1️⃣ Sunday / Holiday
     *  2️⃣ No attendance record → Absent
     *  3️⃣ Stored holiday record
     *  4️⃣ Leave
     *  5️⃣ Stored "Absent"
     *  6️⃣ Present logic (late, half-day, second-half leave etc.)
     *
     * @param \App\User $user
     * @param int       $month
     * @param int       $year
     * @return array    Normalized attendance rows
     */
    public static function getMonthlyAttendance($user, $month, $year)
    {
        $start = Carbon::create($year, $month, 1)->startOfDay();
        $end   = $start->copy()->endOfMonth();

        // Time rules pulled from .env with safe defaults
        $morningStart = env('ATTENDANCE_MORNING_START_TIME', '09:00');
        $morningEnd   = env('ATTENDANCE_MORNING_END_TIME', '10:00');
        $halfDayCut   = env('ATTENDANCE_HALFDAY_TIME', '10:15');

        // Holiday list mapped by date: reason
        $holidays     = Holiday::pluck('reason','date')->toArray();

        $records      = [];
        $lateCounter  = 0; // Used for "(Late 1)", "(Late 2)" remark tracking

        // Loop through every day of the month
        while ($start->lte($end)) {

            $date   = $start->toDateString();
            $day    = $start->format('D');
            $reason = $holidays[$date] ?? null;

            // Fetch attendance entry for the user on this day (if exists)
            $attendance = Attendance::where('user_id', $user->id)
                ->where('date', $date)
                ->first();

            /**
             * ATTENDANCE DECISION PRIORITY
             */
            
            // 1️⃣ Weekends OR declared holidays → No attendance expected
            if ($day == 'Sun' || $reason) {
                $records[] = self::formatHolidayDay($date, $day, $reason);
                $start->addDay(); continue;
            }

            // 2️⃣ No entry = Absent day
            if (!$attendance) {
                $records[] = self::formatAbsentDay(null, $date, $day);
                $start->addDay(); continue;
            }

            // 3️⃣ DB flagged this day as holiday
            if ($attendance->status == 'holiday') {
                $records[] = self::formatHolidayDay($date, $day, $reason);
                $start->addDay(); continue;
            }

            // 4️⃣ Leave stored in DB
            if ($attendance->status == 'leave') {
                $records[] = self::formatLeaveDay($attendance, $date, $day);
                $start->addDay(); continue;
            }

            // 5️⃣ DB explicitly marked Absent
            if ($attendance->status == 'absent') {
                $records[] = self::formatAbsentDay($attendance, $date, $day);
                $start->addDay(); continue;
            }

            // 6️⃣ Default → Present logic (late, half day, partial leave)
            $records[] = self::processPresentDay(
                $attendance, $date, $day, $lateCounter,
                $morningStart, $morningEnd, $halfDayCut
            );

            $start->addDay();
        }

        return $records;
    }

    /**
     * ---------------------------------------------------------------
     * calculateSummary()
     * ---------------------------------------------------------------
     * Generates a roll-up monthly summary for salary processing:
     *  ✔ Full days
     *  ✔ Half days
     *  ✔ Leaves
     *  ✔ Absents
     *  ✔ Remaining payable days
     *
     * @param array $allDates   (Generated by getMonthlyAttendance)
     * @param int   $month
     * @param int   $year
     * @return array
     */
    public static function calculateSummary($allDates, $month, $year)
    {
        $holidays = Holiday::pluck('reason','date')->toArray();

        $today     = Carbon::today();
        $first     = Carbon::create($year, $month, 1);

        // If month is current month → stop summary at today
        $lastValid = $first->isSameMonth($today)
            ? $today
            : $first->copy()->endOfMonth();

        $summary = [
            'totalWorkingDays' => 0,
            'totalPresent'     => 0,
            'totalHalfDay'     => 0,
            'totalLeave'       => 0,
            'totalAbsent'      => 0,
            'totalCalc'        => 0, // Used for payroll
            'lessThanHalf'     => 0,
        ];

        // Count valid working days (Excluding Sundays + holidays)
        $cursor = $first->copy();
        while ($cursor->lte($lastValid)) {
            if ($cursor->format("D") !== "Sun"
                && !isset($holidays[$cursor->toDateString()])) {
                $summary['totalWorkingDays']++;
            }
            $cursor->addDay();
        }

        // Count occurrences from dataset
        foreach ($allDates as $day) {

            if (Carbon::parse($day['date'])->gt($lastValid)) continue;

            if ($day['status'] == 'Present') {
                if ($day['calc'] == 1)   $summary['totalPresent']++;
                if ($day['calc'] == 0.5) $summary['totalHalfDay']++;
                if ($day['calc'] == 0)   $summary['lessThanHalf']++;
            }

            if ($day['status'] == 'Absent') $summary['totalAbsent']++;
            if ($day['status'] == 'Leave')  $summary['totalLeave']++;

            if (is_numeric($day['calc'])) $summary['totalCalc'] += $day['calc'];
        }

        return $summary;
    }


    /* ---------------------------------------------------------------
     *  FORMATTERS (Utility functions returning ready-to-display rows)
     * --------------------------------------------------------------- */

    private static function formatHolidayDay($date, $day, $reason)
    {
        return [
            'date'       => $date,
            'day'        => $day,
            'in'         => '-',
            'out'        => '-',
            'status'     => 'Holiday',
            'remarks'    => $reason ? "($reason)" : "-",
            'calc'       => "-",
            'is_edited'  => 0 // Holidays are never admin-edited
        ];
    }

    private static function formatAbsentDay($attendance, $date, $day)
    {
        return [
            'date'       => $date,
            'day'        => $day,

            // If admin manually created an entry for absent → display stored time
            'in'         => $attendance
                            ? Carbon::parse($attendance->created_at)->format('h:i A')
                            : '-',
            'out'        => ($attendance && $attendance->leave_time)
                            ? Carbon::parse($attendance->leave_time)->format('h:i A')
                            : '-',

            'status'     => 'Absent',
            'remarks'    => '',
            'calc'       => 0,
            'is_edited'  => $attendance->is_edited_by_admin ?? 0
        ];
    }

    private static function formatLeaveDay($attendance, $date, $day)
    {
        // Half leave = 0.5 pay credit
        $half = in_array($attendance->secondary_status, [
            'First Half Leave', 'Second Half Leave'
        ]);

        return [
            'date'       => $date,
            'day'        => $day,
            'in'         => '-',
            'out'        => '-',
            'status'     => 'Leave',
            'remarks'    => $attendance->remarks,
            'calc'       => $half ? 0.5 : 0,
            'is_edited'  => $attendance->is_edited_by_admin ?? 0
        ];
    }

    private static function processPresentDay($attendance, $date, $day, &$lateCount, $morningStart, $morningEnd, $halfDayCut)
    {
        // Extract stored check-in time
        $inCarbon = Carbon::parse($attendance->created_at);
        $inTime   = $inCarbon->format('h:i A');

        $remarks  = "";
        $calc     = 1; // Default full day credit

        $timeOnly = $inCarbon->format("H:i");

        // Check if half-day entry based on ENV rules
        if ($timeOnly >= $halfDayCut) {
            $remarks = "Half Day";
            $calc    = 0.5;
        }
        // Otherwise count late arrivals
        elseif ($timeOnly > $morningEnd) {
            $lateCount++;
            $remarks = "(Late $lateCount)";
        }

        $out = "-";

        // If second-half leave exists → adjust hour calculations
        if ($attendance->secondary_status == "Second Half Leave" && $attendance->leave_time) {

            $outCarbon = Carbon::parse("$date ".$attendance->leave_time);
            $out       = $outCarbon->format("h:i A");

            $minutes   = $inCarbon->diffInMinutes($outCarbon);

            // Second half leave: <4.5 hrs = unpaid
            $calc = $minutes < 270 ? 0 : 0.5;

            $remarks = "Partial Off, Worked: "
                . floor($minutes / 60)."h "
                . ($minutes % 60)."m";
        }

        return [
            'date'       => $date,
            'day'        => $day,
            'in'         => $inTime,
            'out'        => $out,
            'status'     => 'Present',
            'remarks'    => $remarks,
            'calc'       => $calc,
            'is_edited'  => $attendance->is_edited_by_admin ?? 0
        ];
    }
}
